### ISSUE TITLE
ReschedulableScheduler NPE

### ISSUE THREAD

**Issue by koeff** [ru-fix/jfix-stdlib#16]
stack_trace:
`java.lang.IllegalStateException: threadInfo must not be null
	at ru.fix.stdlib.concurrency.threads.ThreadPoolGuard.buildDump(ThreadPoolGuard.kt:34)
	at ru.fix.stdlib.concurrency.threads.ThreadPoolGuard.access$buildDump(ThreadPoolGuard.kt:8)
	at ru.fix.stdlib.concurrency.threads.ThreadPoolGuard$1.run(ThreadPoolGuard.kt:23)
	at ru.fix.stdlib.concurrency.threads.ReschedulableScheduler$SelfSchedulableTaskWrapper.run(ReschedulableScheduler.java:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by swarmshine** [comment]
fixed by @koeff
