### ISSUE TITLE
release 1.0.17 test "testSubmitIncrementThroughput" failed

### ISSUE THREAD

**Issue by AnonymousVovus** [ru-fix/jfix-stdlib#24]
Test "testSubmitIncrementThroughput" failed while project is building.
Here is build output
```
gradlew build

> Configure project :
jfix-stdlib-concurrency: Signing key not provided. Disable signing for  project ':jfix-stdlib-concurrency'.
jfix-stdlib-ratelimiter: Signing key not provided. Disable signing for  project ':jfix-stdlib-ratelimiter'.

> Task :jfix-stdlib-ratelimiter:test

ru.fix.stdlib.ratelimiter.ConfigurableRateLimiterTest > On any 1 second time interval taken in any position in time limit is not exceeded under ragged load() STANDARD_ERROR
    [Test worker] INFO ru.fix.stdlib.ratelimiter.ConfigurableRateLimiterTest -
                Start emitting events with rate: 350
                After 5500 ms pause emitting thread.
                Sleep for 2000 ms.
                Resume emitting delays.
                Expected test run time: 10000 ms

    [Test worker] INFO ru.fix.stdlib.ratelimiter.ConfigurableRateLimiterTest - Events emitting is completed.
    [Test worker] INFO ru.fix.stdlib.ratelimiter.ConfigurableRateLimiterTest - Expected rate: 350, actual max rate: 352

ru.fix.stdlib.ratelimiter.ConfigurableRateLimiterTest > On any 1 second time interval taken in any position in time limit is not exceeded under ragged load() PASSED

ru.fix.stdlib.ratelimiter.ConfigurableRateLimiterTest > getRate returns valid rate() PASSED

ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest > testSubmitIncrementThroughput() FAILED
    org.opentest4j.AssertionFailedError: execution timed out after 15000 ms
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:146)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:117)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:99)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:95)
        at org.junit.jupiter.api.Assertions.assertTimeoutPreemptively(Assertions.java:1467)
        at ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest.testSubmitIncrementThroughput(RateLimitedDispatcherTest.kt:24)

ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest > shutdown_tasksCompletedInTimeout_areCompletedNormally() STANDARD_ERROR
    [Test worker] INFO ru.fix.stdlib.ratelimiter.RateLimitedDispatcher - Close called on RateLimitedDispatcher [test-rate-limiter-dispatcher] with state [TERMINATE]

ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest > shutdown_tasksCompletedInTimeout_areCompletedNormally() PASSED

ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest > testComposeIncrementThroughput() FAILED
    org.opentest4j.AssertionFailedError: execution timed out after 15000 ms
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:146)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:117)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:99)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:95)
        at org.junit.jupiter.api.Assertions.assertTimeoutPreemptively(Assertions.java:1467)
        at ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest.testComposeIncrementThroughput(RateLimitedDispatcherTest.kt:33)

ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest > shutdown_tasksNotCompletedInTimeout_areCompletedExceptionally() STANDARD_ERROR
    [Test worker] INFO ru.fix.stdlib.ratelimiter.RateLimitedDispatcher - Close called on RateLimitedDispatcher [test-rate-limiter-dispatcher] with state [TERMINATE]

ru.fix.stdlib.ratelimiter.RateLimitedDispatcherTest > shutdown_tasksNotCompletedInTimeout_areCompletedExceptionally() PASSED

6 tests completed, 2 failed

> Task :jfix-stdlib-ratelimiter:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jfix-stdlib-ratelimiter:test'.
> There were failing tests. See the report at: file:///C:/Users/vmalygin/work/FIX/jfix-stdlib/jfix-stdlib-ratelimiter/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 44s
10 actionable tasks: 3 executed, 7 up-to-date


```

**Comment by AnonymousVovus** [comment]
not relevant
